### ISSUE TITLE
Tags not added to datasets

### ISSUE THREAD

**Issue by alastairotter** [mediahackza/datadesk#23]
Tags are not added to the datasets. 
On this page for eg. the "gni-dashboard" tag is present but not saved to the dataset. 
https://datadesk.dev/manage/edit.php

![tags](https://github.com/mediahackza/datadesk/assets/754366/955c2530-b784-41b8-929a-a335efe8a5dd)

**Comment by CiaranOtter** [comment]
moved table element inside form element in edit and upload pages. This fixed the issue with the post form recognising added tag inputs

**Comment by CiaranOtter** [comment]
Pushed to live site and main branch
