### ISSUE TITLE
Error message when uploading a test .csv

### ISSUE THREAD

**Issue by Fishbone17** [mediahackza/datadesk#33]
Hi Ciaran!

I got this error message when I tried to upload this Google sheet to data desk [https://docs.google.com/spreadsheets/d/1DZv3FRt02QS-eLoj8kSHg1XE_Slq4QJFT2vGkghDJVg/edit#gid=0]

Fatal error: save_data(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;google_sheet_table&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /var/www/datadesk.dev/public_html/datadesk/upload/google_sheet.php on line 36

Will you let me know what I am doing wrong? Thanks!

**Comment by CiaranOtter** [comment]
Hey gemma. This is an error from my side. The component that is handling uploads of google sheets is storing the code without serialising it first. This means that it doesn't recognise that function being called by save data. 

I'll look into it now and should have it fixed soon

**Comment by CiaranOtter** [comment]
The issue should now be fixed
