### ISSUE TITLE
Problem with format in Datadesk

### ISSUE THREAD

**Issue by Fishbone17** [mediahackza/datadesk#34]
Hi Ciaran!

I uploaded a .csv of the following Google Sheet and when I looked at it in DataDesk, it threw out some of the columns. I have attached a screenshot.
<img width="1056" alt="Screenshot 2023-08-15 at 09 22 18" src="https://github.com/mediahackza/datadesk/assets/49756046/ed1d6629-dbc2-460b-bbb7-2568a22824f5">
And the .csv I used. Is it a problem because in the column H04, there is a variable with parentheses? For example: Pasta (excl spaghetti, macaroni)
[Uploading cpi_prices_reformatted - cpi_prices.csv…]()

**Comment by CiaranOtter** [comment]
The parentheses shouldn't be a problem but the commas separating item inside the parentheses would be considered a separate item. I will try to find a way around this.
