### ISSUE TITLE
Passenger rail journeys on Insights@TheOutlier isn't working

### ISSUE THREAD

**Issue by Fishbone17** [mediahackza/datadesk#51]
Hiya! The link for [passenger railway](https://insights.theoutlier.co.za/charts/260/ZAF/transport/za-passenger-rail) data on Insights@TheOutlier isn't working on my side. The chart isn't showing and the description is for Eskom's carbon Dioxide emissions. 
<img width="1322" alt="Screenshot 2023-09-27 at 16 50 48" src="https://github.com/mediahackza/datadesk/assets/49756046/abd3e046-7424-407f-9316-a01df37ad0e7">

**Comment by alastairotter** [comment]
This is fixed. The issue was related to the source details and notes. If these did not exist or were empty it would cause an error. The chart tool now checks for missing fields and only displays them if there is something to be displayed.
