### ISSUE TITLE
Is it possible to add the month to the hover option on Insights.TheOutlier?

### ISSUE THREAD

**Issue by Fishbone17** [mediahackza/datadesk#53]
Hi Ciaran and Alastair, 

I had a thought as I was updating the charts with the latest StatsSA data this morning. Would it be possible to add a month to the date in the hover option? All the best, Gemma R
<img width="828" alt="Screenshot 2023-10-04 at 08 58 06" src="https://github.com/mediahackza/datadesk/assets/49756046/c070a749-0cb4-45ba-8940-fa1c0ad7acd4">

**Comment by alastairotter** [comment]
I added dateFormat option to config.js which defaults to month-year but can also be set to year. 
Charts should have sensible defaults but worth checking.
