### ISSUE TITLE
Quick adjustment for Renewable Energy Kenya in Insights.TheOutlier

### ISSUE THREAD

**Issue by Fishbone17** [mediahackza/datadesk#54]
Hi Alastair and Ciaran.

Here is hopefully a quick fix.

In the Kenya chart there is the following duplication. 'The generation of renewable power, such as solar power and wind energy, in terawatt hours, one trillion watt-hours, for Angola, Kenya.' Would it be possible to remove the mention of Angola?
<img width="1134" alt="Screenshot 2023-10-05 at 07 44 20" src="https://github.com/mediahackza/datadesk/assets/49756046/245528fc-c0ff-405d-86fb-08791edacdb2">

According to Alastair's notes 'Override added to config.js file. Needs manual intervention.'

All the best,
Gemma R

**Comment by alastairotter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Git](https://trello.com/c/8d5XzVdN/32-git)

**Comment by alastairotter** [comment]
Updated
